# Generated by Django 4.1 on 2022-09-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='Data',
        ),
    ]
